# Generated by Django 5.1.5 on 2025-02-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alerttype_monitor_alert_types_alter_alert_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
    ]
